"""create_core_tables

Revision ID: 6a8943269014
Revises: 007_decision_ledger
Create Date: 2026-01-20 13:03:58.349021+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a8943269014'
down_revision: Union[str, None] = '007_decision_ledger'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log')),
    schema='core'
    )
    op.create_index(op.f('ix_core_audit_log_created_at'), 'audit_log', ['created_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False, schema='core')
    op.create_index(op.f('ix_core_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False, schema='core')
    op.create_table('customers',
    sa.Column('customer_code', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('segment', sa.Enum('RETAIL', 'WHOLESALE', 'BULK', 'OEM', 'DISTRIBUTOR', name='customer_segment'), nullable=False),
    sa.Column('payment_terms', sa.Enum('PREPAID', 'NET15', 'NET30', 'NET45', 'NET60', 'NET90', name='payment_terms'), nullable=False),
    sa.Column('price_tier', sa.Enum('ECONOMY', 'STANDARD', 'PREMIUM', 'VIP', name='price_tier'), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    schema='core'
    )
    op.create_index(op.f('ix_core_customers_customer_code'), 'customers', ['customer_code'], unique=False, schema='core')
    op.create_index(op.f('ix_core_customers_tenant_id'), 'customers', ['tenant_id'], unique=False, schema='core')
    op.create_table('employees',
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_LEAVE', 'TERMINATED', 'SUSPENDED', name='employment_status'), nullable=False),
    sa.Column('employment_type', sa.Enum('FULL_TIME', 'PART_TIME', 'TEMPORARY', 'CONTRACTOR', name='employment_type'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('supervisor_id', sa.UUID(), nullable=True),
    sa.Column('work_center', sa.String(length=100), nullable=True),
    sa.Column('default_shift', sa.String(length=50), nullable=True),
    sa.Column('base_monthly_salary', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('burden_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('skill_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employees')),
    schema='core'
    )
    op.create_index(op.f('ix_core_employees_employee_code'), 'employees', ['employee_code'], unique=False, schema='core')
    op.create_index(op.f('ix_core_employees_tenant_id'), 'employees', ['tenant_id'], unique=False, schema='core')
    op.create_table('machines',
    sa.Column('machine_code', sa.String(length=50), nullable=False),
    sa.Column('machine_name', sa.String(length=255), nullable=False),
    sa.Column('machine_type', sa.Enum('CNC', 'PRESS', 'GRINDING', 'ASSEMBLY', 'PACKAGING', 'MANUAL', 'OTHER', name='machine_type'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MAINTENANCE', 'BREAKDOWN', 'RETIRED', name='machine_status'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('work_center', sa.String(length=100), nullable=True),
    sa.Column('line', sa.String(length=50), nullable=True),
    sa.Column('capacity_units_per_hour', sa.Integer(), nullable=True),
    sa.Column('speed_factor', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('available_hours_per_day', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('available_days_per_week', sa.Integer(), nullable=False),
    sa.Column('maintenance_window', sa.Text(), nullable=True),
    sa.Column('last_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('next_maintenance_date', sa.DateTime(), nullable=True),
    sa.Column('shifts_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('power_kw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines')),
    schema='core'
    )
    op.create_index(op.f('ix_core_machines_machine_code'), 'machines', ['machine_code'], unique=False, schema='core')
    op.create_index(op.f('ix_core_machines_tenant_id'), 'machines', ['tenant_id'], unique=False, schema='core')
    op.create_table('overhead_rates',
    sa.Column('year_month', sa.Date(), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('utilities_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('management_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_overhead_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_monthly_overhead', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_available_hours', sa.Integer(), nullable=False),
    sa.Column('calculated_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overhead_rates')),
    sa.UniqueConstraint('tenant_id', 'year_month', name='uq_overhead_rate_period'),
    schema='core'
    )
    op.create_index(op.f('ix_core_overhead_rates_tenant_id'), 'overhead_rates', ['tenant_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_overhead_rates_year_month'), 'overhead_rates', ['year_month'], unique=False, schema='core')
    op.create_table('products',
    sa.Column('product_code', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.Enum('FINISHED_GOOD', 'SEMI_FINISHED', 'RAW_MATERIAL', 'PACKAGING', 'CONSUMABLE', name='product_type'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCONTINUED', 'PENDING_APPROVAL', name='product_status'), nullable=False),
    sa.Column('bom_version', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('min_order_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('order_multiple', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('standard_cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('base_unit', sa.String(length=10), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_product_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    schema='core'
    )
    op.create_index(op.f('ix_core_products_product_code'), 'products', ['product_code'], unique=False, schema='core')
    op.create_index(op.f('ix_core_products_tenant_id'), 'products', ['tenant_id'], unique=False, schema='core')
    op.create_table('suppliers',
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('material_category', sa.Enum('STEEL', 'WOOD', 'PACKAGING', 'CONSUMABLES', 'COMPONENTS', 'OTHER', name='material_category'), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('payment_terms', sa.Enum('PREPAID', 'NET15', 'NET30', 'NET45', 'NET60', 'NET90', name='payment_terms'), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    schema='core'
    )
    op.create_index(op.f('ix_core_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=False, schema='core')
    op.create_index(op.f('ix_core_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False, schema='core')
    op.create_table('tenants',
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('tenant_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'PENDING', 'CANCELLED', name='tenant_status'), nullable=False),
    sa.Column('subscription_level', sa.Enum('STARTER', 'PROFESSIONAL', 'ENTERPRISE', name='subscription_level'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    schema='core'
    )
    op.create_index(op.f('ix_core_tenants_tenant_code'), 'tenants', ['tenant_code'], unique=True, schema='core')
    op.create_index(op.f('ix_core_tenants_tenant_name'), 'tenants', ['tenant_name'], unique=True, schema='core')
    # Tabelas dqa, supply e shared já existem - não criar novamente
    # (auto_repair_logs, data_quality_issues, trust_index_snapshots, decision_runs, 
    #  inventory_ledger_entries, supply_forecasts, supply_rop_configs já foram criadas em migrações anteriores)
    op.create_table('labor_rates',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('base_hourly_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('burden_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('loaded_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['core.employees.id'], name=op.f('fk_labor_rates_employee_id_employees')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labor_rates')),
    sa.UniqueConstraint('tenant_id', 'employee_id', 'effective_date', name='uq_labor_rate_employee_date'),
    schema='core'
    )
    op.create_index(op.f('ix_core_labor_rates_effective_date'), 'labor_rates', ['effective_date'], unique=False, schema='core')
    op.create_index(op.f('ix_core_labor_rates_employee_id'), 'labor_rates', ['employee_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_labor_rates_tenant_id'), 'labor_rates', ['tenant_id'], unique=False, schema='core')
    op.create_table('machine_rates',
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('depreciation_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('energy_cost_per_hour', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('maintenance_cost_per_hour', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['core.machines.id'], name=op.f('fk_machine_rates_machine_id_machines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_rates')),
    sa.UniqueConstraint('tenant_id', 'machine_id', 'effective_date', name='uq_machine_rate_machine_date'),
    schema='core'
    )
    op.create_index(op.f('ix_core_machine_rates_effective_date'), 'machine_rates', ['effective_date'], unique=False, schema='core')
    op.create_index(op.f('ix_core_machine_rates_machine_id'), 'machine_rates', ['machine_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_machine_rates_tenant_id'), 'machine_rates', ['tenant_id'], unique=False, schema='core')
    op.create_table('operations',
    sa.Column('operation_code', sa.String(length=50), nullable=False),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('operation_type', sa.Enum('PRODUCTION', 'SETUP', 'INSPECTION', 'PACKAGING', 'TRANSPORT', name='operation_type'), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('alternative_machines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('std_time_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('setup_time_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('std_time_hours', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('skills_required', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('setup_family', sa.String(length=50), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('min_batch_size', sa.Integer(), nullable=False),
    sa.Column('default_sequence', sa.Integer(), nullable=False),
    sa.Column('is_subcontracted', sa.Boolean(), nullable=False),
    sa.Column('subcontract_cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['core.machines.id'], name=op.f('fk_operations_machine_id_machines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations')),
    schema='core'
    )
    op.create_index(op.f('ix_core_operations_operation_code'), 'operations', ['operation_code'], unique=False, schema='core')
    op.create_index(op.f('ix_core_operations_tenant_id'), 'operations', ['tenant_id'], unique=False, schema='core')
    # decision_approvals já existe - não criar novamente
    op.create_table('bom_items',
    sa.Column('parent_product_id', sa.UUID(), nullable=False),
    sa.Column('component_product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_per', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=10), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=True),
    sa.Column('scrap_factor', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('bom_version', sa.Integer(), nullable=False),
    sa.Column('position_ref', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['component_product_id'], ['core.products.id'], name=op.f('fk_bom_items_component_product_id_products')),
    sa.ForeignKeyConstraint(['operation_id'], ['core.operations.id'], name=op.f('fk_bom_items_operation_id_operations')),
    sa.ForeignKeyConstraint(['parent_product_id'], ['core.products.id'], name=op.f('fk_bom_items_parent_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_items')),
    sa.UniqueConstraint('tenant_id', 'parent_product_id', 'component_product_id', 'sequence', name='uq_bom_parent_component_seq'),
    schema='core'
    )
    op.create_index(op.f('ix_core_bom_items_component_product_id'), 'bom_items', ['component_product_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_bom_items_parent_product_id'), 'bom_items', ['parent_product_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_bom_items_tenant_id'), 'bom_items', ['tenant_id'], unique=False, schema='core')
    # Não remover event_outbox e event_dlq - já existem e são necessárias
    op.alter_column('copilot_action_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('copilot_action_logs', 'executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('copilot_action_logs', 'rollback_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('copilot_action_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('copilot_action_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_index(op.f('ix_copilot_action_logs_plan_id'), 'copilot_action_logs', ['plan_id'], unique=False)
    op.create_index(op.f('ix_copilot_action_logs_tenant_id'), 'copilot_action_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_copilot_action_logs_user_id'), 'copilot_action_logs', ['user_id'], unique=False)
    op.alter_column('copilot_conversation', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_copilot_conversation_actor_id'), 'copilot_conversation', ['actor_id'], unique=False)
    op.create_index(op.f('ix_copilot_conversation_tenant_id'), 'copilot_conversation', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('uq_copilot_daily_feedback_tenant_date'), 'copilot_daily_feedback', type_='unique')
    op.drop_index(op.f('idx_copilot_daily_feedback_tenant_date'), table_name='copilot_daily_feedback')
    op.create_index('idx_copilot_daily_feedback_tenant_date', 'copilot_daily_feedback', ['tenant_id', 'date'], unique=True)
    op.create_index(op.f('ix_copilot_daily_feedback_tenant_id'), 'copilot_daily_feedback', ['tenant_id'], unique=False)
    op.alter_column('copilot_decision_pr', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_copilot_decision_pr_tenant_id'), 'copilot_decision_pr', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_copilot_message_conversation_id'), 'copilot_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_copilot_message_tenant_id'), 'copilot_message', ['tenant_id'], unique=False)
    op.add_column('copilot_rag_chunk', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_copilot_rag_chunk_tenant_id'), 'copilot_rag_chunk', ['tenant_id'], unique=False)
    op.drop_column('copilot_rag_chunk', 'metadata')
    op.alter_column('copilot_suggestion', 'validation_passed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_copilot_suggestion_actor_id'), 'copilot_suggestion', ['actor_id'], unique=False)
    op.create_index(op.f('ix_copilot_suggestion_correlation_id'), 'copilot_suggestion', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_copilot_suggestion_tenant_id'), 'copilot_suggestion', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_suggestion_tenant_id'), table_name='copilot_suggestion')
    op.drop_index(op.f('ix_copilot_suggestion_correlation_id'), table_name='copilot_suggestion')
    op.drop_index(op.f('ix_copilot_suggestion_actor_id'), table_name='copilot_suggestion')
    op.alter_column('copilot_suggestion', 'validation_passed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('copilot_rag_chunk', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_copilot_rag_chunk_tenant_id'), table_name='copilot_rag_chunk')
    op.drop_column('copilot_rag_chunk', 'chunk_metadata')
    op.drop_index(op.f('ix_copilot_message_tenant_id'), table_name='copilot_message')
    op.drop_index(op.f('ix_copilot_message_conversation_id'), table_name='copilot_message')
    op.drop_index(op.f('ix_copilot_decision_pr_tenant_id'), table_name='copilot_decision_pr')
    op.alter_column('copilot_decision_pr', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_copilot_daily_feedback_tenant_id'), table_name='copilot_daily_feedback')
    op.drop_index('idx_copilot_daily_feedback_tenant_date', table_name='copilot_daily_feedback')
    op.create_index(op.f('idx_copilot_daily_feedback_tenant_date'), 'copilot_daily_feedback', ['tenant_id', 'date'], unique=False)
    op.create_unique_constraint(op.f('uq_copilot_daily_feedback_tenant_date'), 'copilot_daily_feedback', ['tenant_id', 'date'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_copilot_conversation_tenant_id'), table_name='copilot_conversation')
    op.drop_index(op.f('ix_copilot_conversation_actor_id'), table_name='copilot_conversation')
    op.alter_column('copilot_conversation', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_copilot_action_logs_user_id'), table_name='copilot_action_logs')
    op.drop_index(op.f('ix_copilot_action_logs_tenant_id'), table_name='copilot_action_logs')
    op.drop_index(op.f('ix_copilot_action_logs_plan_id'), table_name='copilot_action_logs')
    op.alter_column('copilot_action_logs', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('copilot_action_logs', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('copilot_action_logs', 'rollback_until',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('copilot_action_logs', 'executed_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('copilot_action_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'executed'::character varying"),
               existing_nullable=False)
    op.create_table('event_dlq',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_outbox_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('retry_attempt', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_outbox_id'], ['event_outbox.id'], name=op.f('fk_event_dlq_outbox')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_dlq'))
    )
    op.create_index(op.f('idx_event_dlq_created'), 'event_dlq', ['created_at'], unique=False)
    op.create_table('event_outbox',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('aggregate_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_outbox')),
    sa.UniqueConstraint('tenant_id', 'aggregate_id', 'event_type', name=op.f('uq_event_outbox_idempotency'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_event_outbox_tenant'), 'event_outbox', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_event_outbox_pending'), 'event_outbox', ['status', 'created_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('ix_core_bom_items_tenant_id'), table_name='bom_items', schema='core')
    op.drop_index(op.f('ix_core_bom_items_parent_product_id'), table_name='bom_items', schema='core')
    op.drop_index(op.f('ix_core_bom_items_component_product_id'), table_name='bom_items', schema='core')
    op.drop_table('bom_items', schema='core')
    op.drop_index(op.f('ix_shared_decision_approvals_decision_id'), table_name='decision_approvals', schema='shared')
    op.drop_index(op.f('ix_shared_decision_approvals_approver_id'), table_name='decision_approvals', schema='shared')
    op.drop_table('decision_approvals', schema='shared')
    op.drop_index(op.f('ix_core_operations_tenant_id'), table_name='operations', schema='core')
    op.drop_index(op.f('ix_core_operations_operation_code'), table_name='operations', schema='core')
    op.drop_table('operations', schema='core')
    op.drop_index(op.f('ix_core_machine_rates_tenant_id'), table_name='machine_rates', schema='core')
    op.drop_index(op.f('ix_core_machine_rates_machine_id'), table_name='machine_rates', schema='core')
    op.drop_index(op.f('ix_core_machine_rates_effective_date'), table_name='machine_rates', schema='core')
    op.drop_table('machine_rates', schema='core')
    op.drop_index(op.f('ix_core_labor_rates_tenant_id'), table_name='labor_rates', schema='core')
    op.drop_index(op.f('ix_core_labor_rates_employee_id'), table_name='labor_rates', schema='core')
    op.drop_index(op.f('ix_core_labor_rates_effective_date'), table_name='labor_rates', schema='core')
    op.drop_table('labor_rates', schema='core')
    op.drop_index(op.f('ix_supply_supply_rop_configs_tenant_id'), table_name='supply_rop_configs', schema='supply')
    op.drop_index(op.f('ix_supply_supply_rop_configs_sku_id'), table_name='supply_rop_configs', schema='supply')
    op.drop_table('supply_rop_configs', schema='supply')
    op.drop_index(op.f('ix_supply_supply_forecasts_tenant_id'), table_name='supply_forecasts', schema='supply')
    op.drop_index(op.f('ix_supply_supply_forecasts_sku_id'), table_name='supply_forecasts', schema='supply')
    op.drop_index(op.f('ix_supply_supply_forecasts_forecast_date'), table_name='supply_forecasts', schema='supply')
    op.drop_table('supply_forecasts', schema='supply')
    op.drop_index(op.f('ix_supply_inventory_ledger_entries_tenant_id'), table_name='inventory_ledger_entries', schema='supply')
    op.drop_index(op.f('ix_supply_inventory_ledger_entries_sku_id'), table_name='inventory_ledger_entries', schema='supply')
    op.drop_index(op.f('ix_supply_inventory_ledger_entries_date'), table_name='inventory_ledger_entries', schema='supply')
    op.drop_table('inventory_ledger_entries', schema='supply')
    op.drop_index(op.f('ix_shared_decision_runs_tenant_id'), table_name='decision_runs', schema='shared')
    op.drop_index(op.f('ix_shared_decision_runs_proposed_by'), table_name='decision_runs', schema='shared')
    op.drop_table('decision_runs', schema='shared')
    op.drop_index(op.f('ix_dqa_trust_index_snapshots_tenant_id'), table_name='trust_index_snapshots', schema='dqa')
    op.drop_index(op.f('ix_dqa_trust_index_snapshots_entity_type'), table_name='trust_index_snapshots', schema='dqa')
    op.drop_index(op.f('ix_dqa_trust_index_snapshots_entity_id'), table_name='trust_index_snapshots', schema='dqa')
    op.drop_table('trust_index_snapshots', schema='dqa')
    op.drop_index(op.f('ix_dqa_data_quality_issues_tenant_id'), table_name='data_quality_issues', schema='dqa')
    op.drop_index(op.f('ix_dqa_data_quality_issues_entity_id'), table_name='data_quality_issues', schema='dqa')
    op.drop_table('data_quality_issues', schema='dqa')
    op.drop_index(op.f('ix_dqa_auto_repair_logs_tenant_id'), table_name='auto_repair_logs', schema='dqa')
    op.drop_index(op.f('ix_dqa_auto_repair_logs_entity_id'), table_name='auto_repair_logs', schema='dqa')
    op.drop_table('auto_repair_logs', schema='dqa')
    op.drop_index(op.f('ix_core_tenants_tenant_name'), table_name='tenants', schema='core')
    op.drop_index(op.f('ix_core_tenants_tenant_code'), table_name='tenants', schema='core')
    op.drop_table('tenants', schema='core')
    op.drop_index(op.f('ix_core_suppliers_tenant_id'), table_name='suppliers', schema='core')
    op.drop_index(op.f('ix_core_suppliers_supplier_code'), table_name='suppliers', schema='core')
    op.drop_table('suppliers', schema='core')
    op.drop_index(op.f('ix_core_products_tenant_id'), table_name='products', schema='core')
    op.drop_index(op.f('ix_core_products_product_code'), table_name='products', schema='core')
    op.drop_table('products', schema='core')
    op.drop_index(op.f('ix_core_overhead_rates_year_month'), table_name='overhead_rates', schema='core')
    op.drop_index(op.f('ix_core_overhead_rates_tenant_id'), table_name='overhead_rates', schema='core')
    op.drop_table('overhead_rates', schema='core')
    op.drop_index(op.f('ix_core_machines_tenant_id'), table_name='machines', schema='core')
    op.drop_index(op.f('ix_core_machines_machine_code'), table_name='machines', schema='core')
    op.drop_table('machines', schema='core')
    op.drop_index(op.f('ix_core_employees_tenant_id'), table_name='employees', schema='core')
    op.drop_index(op.f('ix_core_employees_employee_code'), table_name='employees', schema='core')
    op.drop_table('employees', schema='core')
    op.drop_index(op.f('ix_core_customers_tenant_id'), table_name='customers', schema='core')
    op.drop_index(op.f('ix_core_customers_customer_code'), table_name='customers', schema='core')
    op.drop_table('customers', schema='core')
    op.drop_index(op.f('ix_core_audit_log_tenant_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_entity_type'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_entity_id'), table_name='audit_log', schema='core')
    op.drop_index(op.f('ix_core_audit_log_created_at'), table_name='audit_log', schema='core')
    op.drop_table('audit_log', schema='core')
    # ### end Alembic commands ###



